#!/bin/bash
# Build bitcoin.conf from the environment, then run bitcoind in the foreground.
#
# RPC is bound to the container network only. It is never published to the host
# in the compose file, and must never be.
set -euo pipefail

DATADIR=/data
CONF="$DATADIR/bitcoin.conf"

: "${RPC_USER:?RPC_USER is required}"
: "${RPC_PASSWORD:?RPC_PASSWORD is required}"
: "${BLAKE2B_HEADLINE:?BLAKE2B_HEADLINE is required, and must not be empty}"

if [ -z "${BLAKE2B_HEADLINE// /}" ]; then
    echo "FATAL: BLAKE2B_HEADLINE is empty. An empty headline satisfies the node's" >&2
    echo "       startup check but makes the consensus rule a no-op, because" >&2
    echo "       std::search with an empty needle always matches. Refusing." >&2
    exit 1
fi

CHAIN="${CHAIN:-regtest}"
PRUNE="${PRUNE:-0}"
ACTIVATION_HEIGHT="${BLAKE2B_ACTIVATION_HEIGHT:-}"
# The headline and the activation height are a pair on regtest, so supply a
# height when the caller did not. Regtest reads its activation height only from
# `-testactivationheight` and leaves BLAKE2b unactivated otherwise, so an empty
# value gave a node that follows SHA256d forever, which is not what this image is
# for. Upstream is making the pairing explicit too: a coming build reads the
# headline as a regtest-only option and throws `-blake2b_headline requires
# -testactivationheight=blake2b@<height>` when it is set without one.
if [ "$CHAIN" = "regtest" ] && [ -z "$ACTIVATION_HEIGHT" ]; then
    ACTIVATION_HEIGHT=1
fi

{
    echo "# generated by entrypoint, do not edit"
    echo "${CHAIN}=1"
    echo "server=1"
    echo "printtoconsole=1"
    echo "rpcuser=${RPC_USER}"
    echo "rpcpassword=${RPC_PASSWORD}"
    echo "blake2b_headline=${BLAKE2B_HEADLINE}"
    [ "$PRUNE" != "0" ] && echo "prune=${PRUNE}"
    [ "${FASTPRUNE:-0}" != "0" ] && echo "fastprune=1"
    echo "fallbackfee=0.0001"
    echo
    echo "[${CHAIN}]"
    echo "rpcbind=0.0.0.0"
    echo "rpcallowip=${RPC_ALLOW_IP:-172.16.0.0/12}"
    echo "rpcport=18443"
    echo "port=18444"
    [ -n "$ACTIVATION_HEIGHT" ] && echo "testactivationheight=blake2b@${ACTIVATION_HEIGHT}"
    [ -n "${BLOCKNOTIFY_URL:-}" ] && echo "blocknotify=wget -q -T 2 -O /dev/null ${BLOCKNOTIFY_URL}"
} > "$CONF"

echo "knots-blake2b: pinned commit $(cat /etc/knots-pinned-commit)"
echo "knots-blake2b: chain=${CHAIN} prune=${PRUNE} activation=${ACTIVATION_HEIGHT:-none}"

exec bitcoind -datadir="$DATADIR" "$@"
